######################################################################
# Automatically generated by qmake (2.01a) Sat Sep 8 03:36:27 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += DEBUG
LIBS += -lopencv_core -lopencv_highgui -lopencv_ml

# Input
HEADERS += canvas.h mainwidget.h
SOURCES += canvas.cpp main.cpp mainwidget.cpp
